# Generated by Django 3.2.7 on 2025-03-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_username', models.CharField(blank=True, max_length=100, null=True)),
                ('u_password', models.CharField(blank=True, max_length=100, null=True)),
                ('u_name', models.CharField(blank=True, max_length=100, null=True)),
                ('u_dob', models.CharField(blank=True, max_length=100, null=True)),
                ('u_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('u_email', models.CharField(blank=True, max_length=100, null=True)),
                ('u_mobile_num', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
